content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view: 
      fields: [title, date]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: post }
      - { name: date, label: Date, type: date }
      - { name: comments, label: Comments, type: boolean, default: false }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: text }
  - name: About
    label: About
    type: file
    path: _pages/about.md
    view: 
      fields: [title]
    fields:
      - { name: title, label: Title, type: string }
      - { name: layout, type: string, hidden: true, default: about }
      - { name: comments, label: Comments, type: boolean, default: false }
      - { name: image, label: Image, type: image }
      - { name: body, label: Body, type: text }